# Generated by Django 5.2 on 2026-06-07 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0004_remove_option_poll_fk'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
